### PR TITLE
Updating maidsafe_client

### PR DESCRIPTION
**Pull request by maqi**
1, pass compilation : cargo build & cargo test
2, correct process for account creation and login
3, resolved some warnings

[Review on Reviewable](https://reviewable.io/reviews/dirvine/maidsafe_client/23)

### CODE REVIEW

**Comment by dirvine** [comment]
Think you may be missing a comma Qi ```src/lib.rs:90:33: 90:49 error: expected `,` or `>` after lifetime name, found `RoutingInterface`
src/lib.rs:90   my_routing : RoutingClient<'a RoutingInterface>,
                                              ^~~~~~~~~~~~~~~~
src/lib.rs:90:30: 90:50 note: did you mean a single argument type &'a Type, or did you mean the comma-separated arguments 'a, Type?
src/lib.rs:90   my_routing : RoutingClient<'a RoutingInterface>,
                                           ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `maidsafe_client`.```

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dirvine/maidsafe_client/23)

**Comment by maqi** [comment]
It compiles properly on my machine.
probably due to different version of rustc being used.
I am currently doing a nightly update and see if it will spin the same error

**Comment by maqi** [comment]
The error does only get reported in the newer version of rustc.
It is not resolved and the PR shall be able to be merged.

**Comment by dirvine** [comment]
Nice one Qi

**Pull request merged**
