### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vtnerd**
Need some help on expectation specifics here.

### CODE REVIEW

**Comment by dirvine** [comment]
Thanks chap, I think you may need to merge with master and push again. 

It's probably worth adding all you can think of to take this lib right up to the c++ level (posix and RESTful interface). We can make most of this post 0.1.0 but it's good to collate it all whilst its fresh in our heads. Likely we will get a team to cut over very soon so it will help target resources as well.

**Comment by vtnerd** [comment]
I started to write more for the Client-API (blob / container), but that started to get massive, so I left it open ended. Do you want me to continue for that too?

**Comment by dirvine** [comment]
Yes please Lee it will give us the target we need. don't worry how big it gets. thx

**Comment by vtnerd** [comment]
Updated.

**Comment by dirvine** [comment]
Excellent, cheers.

**Pull request merged**
